name: CI

on:
  pull_request: {}
  push: { branches: [ master ] }

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  find_gradle_jobs:
    runs-on: ubuntu-18.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - uses: burrunan/gradle-cache-action@v1
        id: set-matrix
        name: set-matrix
        with:
          job-id: testmatrix
          multi-cache-enabled: true
          arguments: --parallel -q testMatrix
  check:
    needs: find_gradle_jobs
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.find_gradle_jobs.outputs.matrix) }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Clear existing docker image cache
        run: docker image prune -af
      - uses: burrunan/gradle-cache-action@v1
        name: Build and test with Gradle (${{matrix.gradle_args}})
        with:
          job-id: ${{matrix.gradle_args}}
          multi-cache-enabled: true
          arguments: --continue --scan ${{matrix.gradle_args}}
      - name: Aggregate test reports with ciMate
        if: always()
        continue-on-error: true
        env:
          CIMATE_PROJECT_ID: 2348n4vl
          CIMATE_CI_KEY: "CI / ${{ runner.os }} / ${{matrix.gradle_args}}"
        run: |
          wget -q https://get.cimate.io/release/linux/cimate
          chmod +x cimate
          ./cimate "**/TEST-*.xml"
  httpclient5_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare .testcontainers.properties
        run: |
          echo "transport.type=httpclient5" > $HOME/.testcontainers.properties
          cat $HOME/.testcontainers.properties
      - uses: burrunan/gradle-cache-action@v1
        name: Build with Gradle
        with:
          job-id: ${{matrix.gradle_args}}
          multi-cache-enabled: true
          arguments: --scan testcontainers:test --tests '*EventStreamTest'
      - name: aggregate test reports with ciMate
        if: always()
        continue-on-error: true
        env:
          CIMATE_PROJECT_ID: 2348n4vl
          CIMATE_CI_KEY: "CI / Apache HttpClient5"
        run: |
          wget -q https://get.cimate.io/release/linux/cimate
          chmod +x cimate
          ./cimate "**/TEST-*.xml"
